# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 259bdba3444595ceb0c337b39b5cc66310f511aa34de0c5b0945ccc6eff23583676f6fa1f8097d3f87b6f4f82ee841d6f279f06b977a4b62c1b550df8aeb8da1

test:
  secret_key_base: b50b6a59f6267c5f39e2d9468665537238e0678a3bd3e185cd959c9e55ad091a3d41e376ad47b95e06a16f325ca2c181d72234f6a9b990c3177e469a4168f217

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
